spring:
  application:
    name: smart-clinic
  
  datasource:
    url: jdbc:mysql://localhost:3306/smart_clinic?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  sql:
    init:
      mode: never
      # Change to 'always' if you want to run schema.sql on startup

server:
  port: 8080
  servlet:
    context-path: /

app:
  name: Smart Clinic
  version: 1.0.0
  jwt:
    secret: your-secret-key-change-this-in-production-must-be-at-least-256-bits
    expiration-ms: 86400000  # 24 hours
    issuer: smart-clinic

logging:
  level:
    com.example.clinic: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
