server:
  port: 8080
app:
  jwt:
    secret: "supersecret_supersecret_supersecret_32bytes"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinicdb
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
